package com.catherine.security;

public class KeySet {

	public final static String KEYSTORE_TYPE = "JKS";// or
														// KeyStore.getDefaultType()
														// for .keystore
	public final static String KEYSTORE_PATH = "assets/productiongg.jks";
	public final static String KEYSTORE_PW = "ggcompany123!";
	public final static String KEYSTORE_ALIAS = "productiongg";
	public final static String KEY_PW = "ggcompany123!";
	public final static String CERTIFICATION_PATH = "assets/productiongg.cer";

	public final static String TRUSTED_CA = "Google Internet Authority G2";
	public final static String GIAG2_URL = "http://pki.google.com/GIAG2.crt";
	public final static String TRUSTED_SSL_HOSTNAME = "attest.android.com";
	public final static String CRT_SAMPLE1_PATH = "assets/sw1.crt";
	public final static String CRT_SAMPLE2_PATH = "assets/sw2.crt";

	public final static String PEM_SAMPLE1 = "-----BEGIN CERTIFICATE-----"
			+ "MIIFRTCCBC2gAwIBAgIQR+EAAAAA6aIEw6FVags7cDANBgkqhkiG9w0BAQsFADBvMQswCQYDVQQG"
			+ "EwJUVzESMBAGA1UEChMJVEFJV0FOLUNBMRowGAYDVQQLExFTZWN1cmUgU1NMIFN1Yi1DQTEwMC4G"
			+ "A1UEAxMnVFdDQSBTZWN1cmUgU1NMIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MB4XDTE3MTAyNzA3"
			+ "MTEzMVoXDTIwMTAyNzE1NTk1OVowgYsxCzAJBgNVBAYTAlRXMQ8wDQYDVQQIEwZUQUlXQU4xEjAQ"
			+ "BgNVBAcTCUthb2hzaXVuZzEtMCsGA1UEChMkU29mdC1Xb3JsZCBJbnRlcm5hdGlvbmFsIENvcnBv"
			+ "cmF0aW9uMQswCQYDVQQLEwJJVDEbMBkGA1UEAwwSKi5jcmF6eWdhbWUuY29tLnR3MIIBIjANBgkq"
			+ "hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlBToE53vEzhYEhYgaBha3DEQhpjwHPWCISqDPgniNnKY"
			+ "7w/CFqEJ7XeEwZwsejFAC+h8rXA7Nddgd4p0FICJMTkO7K9pIsTF+QUpX7N2GXdvcJCp77nfANas"
			+ "RlSPsGHLdhGUVUh07989LDBHcnfzQz9oYBee2y0K0xIHGKKLBWZTzD52PQusrI05Y2VeB3c0eel2"
			+ "Yrcm0jlmOKjtr7Y9vAkzwxO7hI/t31hCq1rKypG372yqJZWifcZ72wLJc0QyilHU2e5nWDQmAKKt"
			+ "cCRddu2xuWC82/D8KnI8ZIsB2MRJA/jkxARMFlCVxiH3bZa2x/xLIj2XFi4MKmXBl6HZRQIDAQAB"
			+ "o4IBvjCCAbowHwYDVR0jBBgwFoAU+AfCaCT/hZXL2x7jM5wqT5cgVnswKQYDVR0OBCIEICG1fqjB"
			+ "GBb7XyVtmaG5HUOHo1kxtQEU0Qvrpo+E9rVWMFYGA1UdHwRPME0wS6BJoEeGRWh0dHA6Ly9zc2xz"
			+ "ZXJ2ZXIudHdjYS5jb20udHcvc3Nsc2VydmVyL1NlY3VyZXNzbF9yZXZva2Vfc2hhMl8yMDE0LmNy"
			+ "bDAdBgNVHREEFjAUghIqLmNyYXp5Z2FtZS5jb20udHcwgYEGCCsGAQUFBwEBBHUwczBEBggrBgEF"
			+ "BQcwAoY4aHR0cDovL3NzbHNlcnZlci50d2NhLmNvbS50dy9jYWNlcnQvc2VjdXJlX3NoYTJfMjAx"
			+ "NC5jcnQwKwYIKwYBBQUHMAGGH2h0dHA6Ly90d2Nhc3Nsb2NzcC50d2NhLmNvbS50dy8wNwYDVR0g"
			+ "BDAwLjAsBgsrBgEEAYK/JQEBGTAdMBsGCCsGAQUFBwIBFg93d3cudHdjYS5jb20udHcwCQYDVR0T"
			+ "BAIwADAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA0GCSqG"
			+ "SIb3DQEBCwUAA4IBAQBZ68H0SnADu51NXvCyFOFdl/XDG6p9O1PsKnDXWnIiSBuS6M0F6SuQm1p/"
			+ "QF9RzK+na2V0d4l2Svg3NQKn3aR1gbNJRKKloGREvAlu1JekCy8O5J6YQSF+Piu59yFV30ZRAXtJ"
			+ "pC/0w2uAvOlDQ3OIDjLEjty4KPxh6n1JeC8lz4z9PqmaocbNndSBrCyqjQv51+GqbX/OPiTlYKou"
			+ "ttaHJPla0RyyeF4J9N64yfRspHK41X3W+e8NJK8H/YImE1l0PWX8Miubphqj2EMcd1x0ujPrDdXR"
			+ "iG5xNxU/3RVO6HwtnAF8bkHePzH8LYb9UAIjigMbTMy6WnyBvpXsa3+i" + "-----END CERTIFICATE-----";
	
	public final static String PEM_SAMPLE2 = "-----BEGIN CERTIFICATE-----"
			+ "MIIGJjCCBQ6gAwIBAgIRANbz9jQV41KrZN7omu1K7AEwDQYJKoZIhvcNAQELBQAwgZYxCzAJBgNV"
			+ "BAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAOBgNVBAcTB1NhbGZvcmQxGjAY"
			+ "BgNVBAoTEUNPTU9ETyBDQSBMaW1pdGVkMTwwOgYDVQQDEzNDT01PRE8gUlNBIE9yZ2FuaXphdGlv"
			+ "biBWYWxpZGF0aW9uIFNlY3VyZSBTZXJ2ZXIgQ0EwHhcNMTYwNTE3MDAwMDAwWhcNMTgwNjI4MjM1"
			+ "OTU5WjCCARgxCzAJBgNVBAYTAlRXMQ4wDAYDVQQREwUxMTU3ODEPMA0GA1UECBMGVEFJV0FOMQ8w"
			+ "DQYDVQQHEwZUQUlQRUkxNjA0BgNVBAkTLU5vLjk5LTEwLCBTZWMuIDIsIE5hbmdhbmcgUmQuLCBO"
			+ "YW5nYW5nIERpc3QuLDEtMCsGA1UEChMkU29mdC1Xb3JsZCBJbnRlcm5hdGlvbmFsIENvcnBvcmF0"
			+ "aW9uMQswCQYDVQQLEwJJVDEoMCYGA1UECxMfUHJvdmlkZWQgYnkgR2xvYmFsIERpZ2l0YWwgSW5j"
			+ "LjEfMB0GA1UECxMWR2xvYmFsVHJ1c3RTU0xXaWxkY2FyZDEYMBYGA1UEAwwPKi5teWdhbWUuY29t"
			+ "LnR3MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs4bI4NbypPGEKGKvI9u+QO/tjogk"
			+ "3O5B44gCsB2M7uM0+rK0xzN8uQoZtRWU9WyWfWWJktan8k74xGkDYrdZvLREjWXFdidZ4MqdlG7y"
			+ "TVWi/tNIXM9Id+MWh+MJ8CsHkgXxumfHHR6TXM/iASu+/bXlyMn2pTdkBUCk1K+Lz/LTQLLcNU8A"
			+ "RAvdAaLXuedS3aTK4iojD37ZBGzLvBxmliuei2IKWUdRzKsI79rr49e26KDuN9jt/LfiP8xuBQjn"
			+ "/kIQT4xIMnkIN9uT57Jok19cg20dFrMxLQrD3MYZOeRPK1lNBrM5UFPDNZzuUBXfHpgm1F8dVDXG"
			+ "hIkM5nCp5QIDAQABo4IB6DCCAeQwHwYDVR0jBBgwFoAUmvMr2s+tT7YvuypISCoStxtCwSQwHQYD"
			+ "VR0OBBYEFBCSXfw+yZoxPnURI4uHdAtGH8dFMA4GA1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAA"
			+ "MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBQBgNVHSAESTBHMDsGDCsGAQQBsjEBAgED"
			+ "BDArMCkGCCsGAQUFBwIBFh1odHRwczovL3NlY3VyZS5jb21vZG8uY29tL0NQUzAIBgZngQwBAgIw"
			+ "WgYDVR0fBFMwUTBPoE2gS4ZJaHR0cDovL2NybC5jb21vZG9jYS5jb20vQ09NT0RPUlNBT3JnYW5p"
			+ "emF0aW9uVmFsaWRhdGlvblNlY3VyZVNlcnZlckNBLmNybDCBiwYIKwYBBQUHAQEEfzB9MFUGCCsG"
			+ "AQUFBzAChklodHRwOi8vY3J0LmNvbW9kb2NhLmNvbS9DT01PRE9SU0FPcmdhbml6YXRpb25WYWxp"
			+ "ZGF0aW9uU2VjdXJlU2VydmVyQ0EuY3J0MCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5jb21vZG9j"
			+ "YS5jb20wKQYDVR0RBCIwIIIPKi5teWdhbWUuY29tLnR3gg1teWdhbWUuY29tLnR3MA0GCSqGSIb3"
			+ "DQEBCwUAA4IBAQCyyKRZQjHmZeVjcNiFsZtNTuANIs/nYZvSxW7fj2lbZq9Xow2m6JJ9cVhoMObh"
			+ "ip32BM6a7lk/lDGtmyHlxv22e4Nzz0AUUphUuBGQGR4M9wKh5E3YMuDbnu8w/tDZeJFCyl0V1RQE"
			+ "Yt8va6VQU9sWCb5NDcxSHU5e2aLkQVgrvBXfJrs/8zUh9yVAHqfBuAP/iK1GA1JMCqv8Oogl1yP0"
			+ "ns6H1r6kcwVFGSXMl8GA3Uo4aiiojHWnxkYZY5nuyQ1kr+S1oZkR3n9GBpRkdmCexKZJu4tdSQKW"
			+ "6A3PkcyswrT0RFVaty83y6GOU83HA+eXvfF4gm8L9hjNr6VT/A/u" + "-----END CERTIFICATE-----";
}